owner: deckerci
repo: status-ci

sites:
  - name: Decker Home
    url: https://derailed.one
  - name: Decker API
    url: https://derailed.one/api

status-website:
  # TODO: Change Logo URL
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Decker Status
  introTitle: "**Decker Status** OSS"
  introMessage: This is the **Open Source** Status Page for Decker's Services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
