owner: itchci
repo: status

sites:
  - name: Itch Legacy Home
    url: https://derailed.one
    expectedStatusCodes:
      - 200
      - 404
  - name: Itch Legacy API
    url: https://derailed.one/api

status-website:
  # TODO: Change Logo URL
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/itchci/status/master/assets/itchy.svg
  name: Itch Status
  theme: night
  introTitle: "**Itch Status** OSS"
  introMessage: This is the **Open Source** Status Page for Itch's Services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Itchy"
  commitAuthorEmail: "statusbot@itch.ci"
