owner: derailed-org
repo: status

sites:
  - name: Derailed Home
    url: https://derailed.one
    expectedStatusCodes:
      - 200
      - 404
  - name: Derailed API
    url: https://derailed.one/api

status-website:
  # TODO: Change Logo URL
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/derailed-org/status/master/assets/derailed-mascot.svg
  name: Derailed Status
  cname: status.derailed.one
  theme: night
  introTitle: "**Derailed Status** OSS"
  introMessage: This is the **Open Source** Status Page for Derailed's Services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Derailer"
  commitAuthorEmail: "statusbot@derailed.org"
